### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by Natx-C** [Stazyu/Yu-Bot#1]
bisa buat self nda bang?

**Comment by Stazyu** [comment]
Bisa, habis nambahin database nanti sekalian tambahin mode self/publik juga

**Comment by Natx-C** [comment]
> Bisa, habis nambahin database nanti sekalian tambahin mode self/publik juga

siap banggg

**Comment by Stazyu** [comment]
SelfBot sudah ditambahkan ya

**Comment by Natx-C** [comment]
> SelfBot sudah ditambahkan ya

wokeh mantap bangg
