### ISSUE TITLE
gc 500+

### ISSUE THREAD

**Issue by KiZakiXD** [Stazyu/Yu-Bot#2]
4.2.0 bayles kdg kerestat keknya g spport
tapi 4.1.0 bisa itu di sc gw di sc lu gtw kbnyakan sc gitu

**Comment by Stazyu** [comment]
Iyaa ga support, kemarin nyoba.. sekarang lupa belum tak fix lagi

**Comment by KiZakiXD** [comment]
semoga harimu senin terus
